language: python

python:
 - "3.6"

install:
 - pip install black isort flake8 codecov

script:
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff .
 - coverage run --omit="*/tests/*" setup.py test

after_success:
 - codecov
